name: SpendingMonitor
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  sqflite: ^2.2.8+2
  flutter_speed_dial: ^6.2.0
  events_emitter: ^0.5.2
  sqflite_common_ffi: ^2.2.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.1
  currency_picker: ^2.0.16
  material_symbols_icons: ^4.2741.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  file_picker: ^8.0.0+1
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/currencies.json
    - assets/images/LogoSpendingMonitor.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/LogoSpendingMonitor.png
  min_sdk_android: 21
